# Generated by Django 4.1.3 on 2022-11-28 10:48

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('doctor_request', models.CharField(choices=[('accepted', 'Accepted'), ('waiting', 'Waiting'), ('rejected', 'Rejected')], default='waiting', max_length=20)),
                ('explanation', models.CharField(default='', max_length=500)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('meeting_name', models.CharField(max_length=200)),
                ('meeting_description', models.CharField(max_length=1000)),
                ('meeting_url', models.CharField(max_length=1000)),
                ('meeting_start_time', models.DateTimeField()),
                ('meeting_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('attendees', models.ManyToManyField(related_name='attendees', through='appointment.AppointmentRequest', to=settings.AUTH_USER_MODEL)),
                ('meeting_host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_host', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('available_time', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('reserved', models.BooleanField(default=0)),
                ('available_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='available_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.meetingroom'),
        ),
    ]
