# Generated by Django 4.1.3 on 2023-01-04 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='request_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='explanation',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_room', to='appointment.meetingroom'),
        ),
    ]
