# Generated by Django 4.1.3 on 2023-02-02 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('appointment', '0002_appointmentrequest_request_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient', to='patient.patients'),
        ),
    ]
