# Generated by Django 4.1.3 on 2023-02-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_meetingroom_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='documents_checked',
            field=models.BooleanField(default=False),
        ),
    ]
