# Generated by Django 4.1.3 on 2023-02-08 18:49

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='professional_awards_degree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='professional_memberships',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='scientific_publications',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='treatment_methods',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vocational_courses_conferences',
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to='authentication.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(choices=[('PROFESSOR DOCTOR', 'Professor Doctor'), ('ASSOCIATE PROFESSOR', 'Associate Professor'), ('SPECIALIST', 'Specialist'), ('LECTURER', 'Lecturer')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.FileField(blank=True, default='default_id_card.png', upload_to='doctors/id_card_upload'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default_1.png', upload_to='doctors/avatar_upload', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'png'])]),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, max_length=8)),
                ('treatment_methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('scientific_publications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None)),
                ('professional_memberships', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None)),
                ('professional_awards_degree', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None)),
                ('vocational_courses_conferences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None)),
                ('client_cost', models.IntegerField()),
                ('currency_unit', models.CharField(choices=[('DOLLAR', '$'), ('EURO', '€'), ('TL', '₺')], max_length=6)),
                ('patient_consultation', models.BooleanField(default=False)),
                ('academic_consultation', models.BooleanField(default=False)),
                ('cv', models.FileField(blank=True, default='default_cv.png', upload_to='doctors/cv_upload')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='authentication.profile')),
            ],
        ),
    ]
