# Generated by Django 4.1.3 on 2023-02-28 22:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='employee',
            name='about_doctor',
            field=models.CharField(default=1, max_length=700),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='hobbies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='orcid_account',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pubmed_account',
            field=models.URLField(null=True),
        ),
    ]
