# Generated by Django 4.1.3 on 2023-03-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_phone_employee_about_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='currency_unit',
            field=models.CharField(choices=[('dollar', '$'), ('euro', '€'), ('tl', '₺')], max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(choices=[('professor doctor', 'Professor Doctor'), ('associate professor', 'Associate Professor'), ('specialist', 'Specialist'), ('lecturer', 'Lecturer')], max_length=30),
        ),
    ]
