# Generated by Django 4.1.3 on 2023-02-02 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastMedicalIllnesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('illness', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unspecified', 'Unspecified')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('illnesses', models.CharField(max_length=100)),
                ('describtion', models.CharField(max_length=1000)),
                ('past_illnesses', models.ManyToManyField(to='patient.pastmedicalillnesses')),
                ('primary_doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='primary_doctor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('occupation', models.CharField(max_length=200)),
                ('is_marital', models.BooleanField()),
                ('are_children', models.BooleanField()),
                ('use_alcohol', models.BooleanField()),
                ('how_often_use_alcohol', models.CharField(max_length=250)),
                ('use_smoke', models.BooleanField()),
                ('used_since', models.IntegerField()),
                ('use_former_smoke', models.BooleanField()),
                ('use_chew_tobacco', models.BooleanField()),
                ('packs_per_days', models.CharField(choices=[('0', 'Zero'), ('quarter', 'Quarter'), ('half', 'Half'), ('1', 'One'), ('2', 'Two'), ('more', 'More')], default='0', max_length=50)),
                ('use_drugs', models.BooleanField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_patient', to='patient.patients')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('file', models.FileField(blank=True, upload_to=None)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_files', to='patient.patients')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PastMedicalOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('operation', models.CharField(max_length=500)),
                ('hospital', models.CharField(max_length=200)),
                ('operation_date', models.DateField()),
                ('hospitalization_time', models.CharField(max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_patient', to='patient.patients')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('instructions_of_use', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_patient', to='patient.patients')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyHealthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('members', models.CharField(choices=[('maternal grandmother', 'Maternal Grandmother'), ('maternal grandfather', 'Maternal Grandfather'), ('paternal grandmother', 'Paternal Grandmother'), ('paternal grandfather', 'Paternal Grandfather'), ('mother', 'Mother'), ('father', 'Father'), ('brother', 'Brother'), ('sister', 'Sister'), ('son', 'Son'), ('daughters', 'Daughters')], max_length=30)),
                ('major_medical_problems', models.CharField(max_length=200)),
                ('if_deceased_causes', models.CharField(max_length=300, null=True)),
                ('age_at_date', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_patient', to='patient.patients')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('allergie', models.CharField(max_length=200)),
                ('reactions', models.CharField(max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies_patient', to='patient.patients')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
