# Generated by Django 4.1.3 on 2023-02-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMembersNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FrequencyOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GenderOptionsNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pastmedicalillnesses',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='pastmedicalillnesses',
            name='updated_modified_date',
        ),
        migrations.AlterField(
            model_name='familyhealthhistory',
            name='age_at_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='familyhealthhistory',
            name='major_medical_problems',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='describtion',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientsfile',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='how_often_use_alcohol',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='occupation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socialhistory',
            name='packs_per_days',
            field=models.CharField(choices=[('0', '0'), ('quarter', 'Quarter'), ('half', 'Half'), ('1', '1'), ('2', '2'), ('more', 'More')], default='0', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='symptoms',
            field=models.ManyToManyField(to='patient.symptoms'),
        ),
    ]
