# Generated by Django 4.1.3 on 2023-02-27 08:28

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_familymembersnames_frequencyofuse_genderoptionsnames_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsfile',
            name='file',
            field=models.FileField(blank=True, upload_to=patient.models.user_directory_path),
        ),
    ]
